# PyTorchとは？
https://colab.research.google.com/github/YutaroOgawa/pytorch_tutorials_jp/blob/main/notebook/1_Learning%20PyTorch/1_1_tensor_tutorial_jp.ipynb

In [1]:
%matplotlib inline

In [2]:
from __future__ import print_function

import torch

In [3]:
x = torch.empty(5, 3)

In [4]:
x = torch.rand(5, 3)

In [5]:
x = torch.zeros_like(x, dtype=torch.long)

In [6]:
x = torch.tensor([5.5, 3])

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6812, -1.3304,  1.0144],
        [-0.0796, -2.1058,  0.2453],
        [-0.2965,  0.0273, -0.2091],
        [ 0.6318,  0.1741,  1.1260],
        [ 1.0322,  0.4109, -1.5252]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.7459, -0.7025,  1.3985],
        [ 0.0850, -1.3019,  0.6968],
        [-0.0437,  0.7442,  0.7268],
        [ 0.6384,  0.2293,  1.6989],
        [ 1.1339,  1.1870, -0.8210]])


In [10]:
torch.add(x, y)

tensor([[ 0.7459, -0.7025,  1.3985],
        [ 0.0850, -1.3019,  0.6968],
        [-0.0437,  0.7442,  0.7268],
        [ 0.6384,  0.2293,  1.6989],
        [ 1.1339,  1.1870, -0.8210]])

In [11]:
y.add_(x)

tensor([[ 0.7459, -0.7025,  1.3985],
        [ 0.0850, -1.3019,  0.6968],
        [-0.0437,  0.7442,  0.7268],
        [ 0.6384,  0.2293,  1.6989],
        [ 1.1339,  1.1870, -0.8210]])

In [12]:
x[:, 1]

tensor([-1.3304, -2.1058,  0.0273,  0.1741,  0.4109])

In [13]:
a = torch.ones(5)

In [14]:
b = a.numpy()

In [15]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [16]:
if torch.cuda.is_available():
    device = torch.device("cuda")  # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))  # ``.to`` can also change dtype together!

tensor([[ 1.6812, -0.3304,  2.0144],
        [ 0.9204, -1.1058,  1.2453],
        [ 0.7035,  1.0273,  0.7909],
        [ 1.6318,  1.1741,  2.1260],
        [ 2.0322,  1.4109, -0.5252]], device='cuda:0')
tensor([[ 1.6812, -0.3304,  2.0144],
        [ 0.9204, -1.1058,  1.2453],
        [ 0.7035,  1.0273,  0.7909],
        [ 1.6318,  1.1741,  2.1260],
        [ 2.0322,  1.4109, -0.5252]], dtype=torch.float64)
